---
name: golangci-lint

on:
  push:
    branches: ['main', 'release-*']
  pull_request:
    branches: ['*']

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.24"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.5
        args: -E gosec --timeout=6m
